### ISSUE TITLE
Zipball configuration

### ISSUE THREAD

**Issue by hotrush** [vtsykun/packeton#12]
I've got this error:

```
- Installing package/name (0.1.1): Downloading (failed)    Failed to download  package/name  from dist: The "https://example.com/zipball/package/name /1ccc92dc6d3aec958cd087b57c8d6bc6e0d7c6e3.zip" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing  package/name  (0.1.1): Cloning 1ccc92dc6d from cache
```

What should i change in config to change example.com to my domain?

**Comment by hotrush** [comment]
Also i've already changed PACKAGIST_DIST_HOST to my domain but it doesn't work

**Comment by vtsykun** [comment]
Hi,
Please use `PACKAGIST_HOST: pkg.okvpn.org` env. if you use the docker installation. I'll update docker documentation. 
Also after change `PACKAGIST_HOST` you will need:
* update package from UI or cli (click on button "Update"), because the package metadata saved into database. 
* and run `composer update` to update composer.lock

**Comment by hotrush** [comment]
@vtsykun hm, that is strange because i have `PACKAGIST_HOST` defined from start in container environment and it had no any affect.

Now i've updated package from UI (after `PACKAGIST_DIST_HOST` change) and seems it works. Thanks.
