### ISSUE TITLE
What are the github.com ssh keys in the docker container used for?

### ISSUE THREAD

**Issue by PatrickHollweck** [vtsykun/packeton#21]
Hey,
First of all thanks for maintaining this awesome package. 👍

I just have a quick question.
I installed packeton on a server using docker and found that there were 3 ssh keys for github.com saved in the ~/.ssh file.

What are these keys used for?

**Comment by vtsykun** [comment]
Hi @PatrickHollweck 

What do you mean? If you are mean `~/.ssh/known_hosts`, these keys are used to verify the identity of the remote host, thus protecting against impersonation or mitm attacks. You can change `PRIVATE_REPO_DOMAIN_LIST` to disable save ssh fingerprints, see [here](https://github.com/vtsykun/packagist-docker/blob/master/docker-entrypoint.sh#L8)

**Comment by PatrickHollweck** [comment]
For some reason there the `~/.ssh` is not a directory but a file in my container.
This file contains 3 public keys. They do not follow the usual format though.

Here is the content of the file with the key part blurred out. I am almost certain that we did not put those keys there since we use GitLab and not Github internally.
We do host the container with Plesk though, maybe it put it there, but I doubt it.

This is the content of `more ~/.ssh` (I blurred out the key for security reasons)

![keys](https://user-images.githubusercontent.com/20997737/83260173-9a6bd000-a1b9-11ea-8984-9350fcc72694.PNG)

**Comment by vtsykun** [comment]
Hi @PatrickHollweck 
I don't see this file in my docker container. In any cases you can ignore it, because this public keys can not used for login by SSH key authentication. This key was taken by command `ssh-keyscan -t rsa,dsa github.com` and it saved each time then you clone repo by ssh 

![Selection_176](https://user-images.githubusercontent.com/21358010/83265880-cba0cc00-a1ca-11ea-8413-5e53a198af84.png)

![Selection_177](https://user-images.githubusercontent.com/21358010/83266538-a2cd0680-a1cb-11ea-9513-fd658f6b484f.png)

**Comment by PatrickHollweck** [comment]
Oh! I see, Thanks for investigating this :)
