### ISSUE TITLE
[FEATURE REQUEST] LDAP authentification

### ISSUE THREAD

**Issue by sajphon** [vtsykun/packeton#26]
Would it be possible to implement LDAP authentification, with fetching of ldap roles?

**Comment by alinalexandru** [comment]
I am also interested

**Comment by vtsykun** [comment]
Hi @alinalexandru 
Can you help with it? I'll review and merge your PR. Just now I am not have enough free time due to protests activity in Belarus.

Thanks
Uladzimir.

**Comment by ipimpat** [comment]
A better solution could be to add support for external authenticated users using the REMOTE_USER header

That would give the freedom to choose any authentication method you like as long as your web server supports it.

if you e.g. want to authenticate users against and Active Directory, I find it much easier to just join the Linux machine to Active Directory using SSSD and then just configure my web servers to authenticate users via PAM, rather than configure LDAP bindings in every single application directly.
