### ISSUE TITLE
v2.0 Migration issue

### ISSUE THREAD

**Issue by bergo** [vtsykun/packeton#53]
We tried the migration from the latest v1 to v2.0 and it fails.

* we use single docker-container with docker-compose
* (In prior version, we used env-variables in docker-compose to specify the mysql params)
* changed docker-compose to new image, change volume path
* restart recreated the container with new sqlite database. 
* changes in host .env file (linked to .env.local in container) has no effect
* changes in .env in container has no effect

Seems, that the .env files in the single container images are ignored.

**Comment by vtsykun** [comment]
Hi,
This is due to the loading priority of environment variables. Docker define env have a more priority. `DATABASE_URL` define in [Dockerfile](https://github.com/vtsykun/packeton/blob/master/Dockerfile#L69)
So to overwrite it need define env in docker-compose  
```
        environment:
            DATABASE_URL: "mysql://....."
```

`/data/.env` - use to generate and keep a unique secret

**Comment by bergo** [comment]
Yes, this works. Thank you!

Maybe worth to put it in the the upgrade guide ;)
